backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site_html"
    label: "Site HTML"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.html"
        fields:
          - label: "HTML"
            name: "body"
            widget: "code"
            default_language: "html"
